name: privileged
on: workflow_dispatch

jobs:
  privileged:
    runs-on: ubuntu-latest

    steps:
      - name: download-fly
        run: |
          curl -o /tmp/docker-compose.yml -L https://concourse-ci.org/docker-compose.yml
          docker-compose -f "/tmp/docker-compose.yml" up --build
          #sudo curl -o /usr/local/bin/fly -L http://localhost:8080/api/v1/cli?arch=amd64&platform=linux
          #sudo chmod +x /usr/local/bin/fly
          #fly --version
