name: privileged
on: workflow_dispatch

jobs:
  privileged:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run-concourse-and-download-fly
        # NOT A TTY issues: https://github.com/actions/runner/issues/241#issuecomment-924327172
        shell: 'script --return --quiet --command "bash {0}"'
        run: |
          curl -o /tmp/docker-compose.yml -L https://concourse-ci.org/docker-compose.yml
          docker-compose -f "/tmp/docker-compose.yml" up -d --build
          while [ ! -f /usr/local/bin/fly ]
          do
            sudo curl --silent -o /usr/local/bin/fly -L http://localhost:8080/api/v1/cli?arch=amd64&platform=linux
            sleep 5
          done
          sudo chmod +x /usr/local/bin/fly

          fly --verbose -t concourse login -c http://localhost:8080 -u test -p test
          fly --verbose -t concourse execute -c ${{ github.workspace }}/.concourse/helloworld.yml
