name: privileged
on: workflow_dispatch

jobs:
  privileged:
    runs-on: ubuntu-latest
    container:
      image: concourse/concourse
      options: --privileged

    steps:
      - name: simple-task
        run: |
          echo "Hello, world!"
          /usr/local/concourse/bin/concourse
