name: privileged
on: workflow_dispatch

jobs:
  privileged:
    runs-on: ubuntu-latest
    container:

    services:
      concourse:
        image: concourse/concourse
        options: --privileged --entrypoint "/usr/local/concourse/bin/concourse quickstart"
        env:
          CONCOURSE_POSTGRES_HOST: postgres
          CONCOURSE_POSTGRES_USER: concourse_user
          CONCOURSE_POSTGRES_PASSWORD: concourse_pass
          CONCOURSE_POSTGRES_DATABASE: concourse
          CONCOURSE_ADD_LOCAL_USER: test:test
          CONCOURSE_MAIN_TEAM_LOCAL_USER: test

      postgres:
        image: postgres
        env:
          POSTGRES_USER: concourse_user
          POSTGRES_PASSWORD: concourse_pass
          POSTGRES_DB: concourse

    steps:
      - name: download-fly
        uses: ubuntu:latest
        run: |
          apt-get update
          apt-get install -y --no-install-recommends curl ca-certificates
          curl -o /usr/local/bin/fly -L http://concourse/api/v1/cli?arch=amd64&platform=linux
          chmod +x /usr/local/bin/fly
          fly --version
