name: privileged
on: workflow_dispatch

jobs:
  privileged:
    runs-on: ubuntu-latest

    services:
      concourse:
        image: cryogenics/concourse-ghactions
        options: --privileged
        ports:
          - 8080/tcp
        env:
          CONCOURSE_POSTGRES_HOST: postgres
          CONCOURSE_POSTGRES_USER: concourse_user
          CONCOURSE_POSTGRES_PASSWORD: concourse_pass
          CONCOURSE_POSTGRES_DATABASE: concourse
          CONCOURSE_ADD_LOCAL_USER: test:test
          CONCOURSE_MAIN_TEAM_LOCAL_USER: test

      postgres:
        image: postgres
        ports:
        - 5432/tcp
        env:
          POSTGRES_USER: concourse_user
          POSTGRES_PASSWORD: concourse_pass
          POSTGRES_DB: concourse

    steps:
      - name: download-fly
        run: |
          sudo curl -o /usr/local/bin/fly -L http://concourse:8080/api/v1/cli?arch=amd64&platform=linux
          sudo chmod +x /usr/local/bin/fly
          fly --version
