#---
#jobs:
#- name: ((first))-job
#  public: true
#  plan:
#  - task: simple-task
#    config:
#      platform: linux
#      image_resource:
#        type: registry-image
#        source: { repository: busybox }
#      run:
#        path: echo
#        args: ["Hello, ((hello))!"]
#- name: level-((number))-job
#  public: true
#  plan:
#  - task: simple-task
#    config:
#      platform: linux
#      image_resource:
#        type: registry-image
#        source: { repository: busybox }
#      run:
#        path: echo
#        args: ["Hello, ((hello))!"]

name: helloworld-withvars
on: workflow_dispatch

jobs:
  ((first))-job:
    runs-on: ubuntu-latest
    env:
      hello: HAL1
    steps:
    - name: simple-task
      uses: docker://busybox:latest
      with:
        entrypoint: /bin/echo
        args: Hello, ${{hello}}!
  level-((number))-job:
    runs-on: ubuntu-latest
    env:
      hello: HAL2
    steps:
    - name: simple-task
      uses: docker://busybox:latest
      with:
        entrypoint: /bin/echo
        args: Hello, ${{hello}}!
